micronaut:
  application:
    name: oda-media-service
  security:
    authentication: cookie
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
  http.services.youtube.url: https://youtube.googleapis.com
flyway:
  datasources:
    default:
      enabled: true
jpa:
  default:
    entity-scan:
        packages: 'io.github.opendonationassistant'
